# List packages you wish to install in your environment under
# the `[install]` table
[install]
cargo.pkg-path = "cargo"
rustc.pkg-path = "rustc"
rust-analyzer.pkg-path = "rust-analyzer"
clippy.pkg-path = "clippy"
rustfmt.pkg-path = "rustfmt"
cargo-watch.pkg-path = "cargo-watch"
cargo-semver-checks.pkg-path = "cargo-semver-checks"
cargo-flamegraph.pkg-path = "cargo-flamegraph"
# hello.pkg-path = "hello"
# nodejs = { version = "^18.4.2", pkg-path = "nodejs_18" }

# Set your activation hook ( run when entering the environment )
# You can write this inline with the `script` field, or provide a
# relative path to a file using the `file` field.
# [hook]
# script = """
#   echo "it's gettin flox in here";
# """

